- name: creation of vm's in aws
  hosts: local
  connection: local
  vars:
   AMI: ami-0220d79f3f480ecf5
   SECURITY_GROUP: sg-0039b9fd218e26beb
   ENVIROMENT: dev
   INSTANCES: 
     - mongodb
     - catalogue
   INFRA: creation
   ZONE: tilakrepalle.in

  tasks:

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: '{{ item }}-{{ ENVIROMENT }}'
        instance_type: t3.micro
        security_group: "{{ SECURITY_GROUP }}"
        network:
          assign_public_ip: true
        image_id: "{{ AMI }}"
        tags:
          Name: '{{ item }}-{{ ENVIROMENT }}'
          Enviroment: "{{ ENVIROMENT }}"
      loop: "{{ INSTANCES }}"
      when: INFRA == "creation"
      register: instance_output

    - name: Print public IPs
      ansible.builtin.debug:
        msg: "Instance {{ item.item }}-{{ ENVIROMENT }} Public IP: {{ item.instances[0].private_ip_address }}"
      loop: "{{ instance_output.results }}"

    - name: Update new.foo.com as an A record with a list of 3 IPs and wait until the changes have been replicated
      amazon.aws.route53:
        state: present
        zone: "{{ ZONE }}"
        record: "{{ item.item }}-{{ ENVIROMENT }}.{{ ZONE }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ instance_output.results }}"
      when: INFRA == "creation"

    - name: Delete new.foo.com A record using the results from the get command
      amazon.aws.route53:
        state: absent
        zone: foo.com
        record: "{{ rec.set.record }}"
        ttl: "{{ rec.set.ttl }}"
        type: "{{ rec.set.type }}"
        value: "{{ rec.set.value }}"
      when: INFRA == "destroy"
      loop: "{{ INSTANCES }}"

      

    